# Generated by Django 2.1.5 on 2020-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.CharField(max_length=18)),
                ('caseNumber', models.CharField(max_length=18)),
                ('caseSubject', models.CharField(max_length=4096)),
                ('caseModule', models.CharField(max_length=64)),
            ],
        ),
    ]
