# Generated by Django 2.1.5 on 2020-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='published',
            field=models.IntegerField(default=0),
        ),
    ]
