# Generated by Django 2.1.5 on 2020-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_case_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='caseDescription',
            field=models.TextField(default='', max_length=10240),
        ),
        migrations.AlterField(
            model_name='case',
            name='caseSubject',
            field=models.CharField(max_length=1024),
        ),
    ]
